public class Global_Constants {
    
    public static final String HN_API = 'https://hacker-news.firebaseio.com';
    
    public static final String HN_API_BestStories = 'https://hacker-news.firebaseio.com/v0/beststories.json?print=pretty';
    
    public static final String HN_API_TopStories = 'https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty';
    
    public static final String HN_API_MaxItemID = 'https://hacker-news.firebaseio.com/v0/maxitem.json?print=pretty';
    
    

}