public class ResponseWrapper{
            public String postedBy;           // String
            public String descendants;  // Number -> String
            public String ItemId;           // Number -> String
            public List<String> kids;   // Array of Numbers -> List of Strings
            public String score;        // Number -> String
            public String UnixTime;         // Number -> String
            public String title;        // String
            public String Itemtype;         // String
            public String url;          // String
        public ResponseWrapper(){
        }
    }